"""fix basket keys again

Revision ID: 08fb8aa4b722
Revises: dd158a80cbda
Create Date: 2024-12-10 21:09:50.867210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fb8aa4b722'
down_revision = 'dd158a80cbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Basket', schema=None) as batch_op:
        batch_op.drop_index('ix_Basket_product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Basket', schema=None) as batch_op:
        batch_op.create_index('ix_Basket_product_id', ['product_id'], unique=False)

    # ### end Alembic commands ###
