"""chnage date to string

Revision ID: 61c44d021fbe
Revises: 4175e4819db3
Create Date: 2024-12-12 19:56:53.350387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c44d021fbe'
down_revision = '4175e4819db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customerorders', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customerorders', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
