"""initial migration

Revision ID: 8cdf1ff35fb7
Revises: b8630fa28bcc
Create Date: 2024-12-09 18:49:29.181195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cdf1ff35fb7'
down_revision = 'b8630fa28bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('Productcategories')
#     op.drop_table('Productsizes')




  
        #batch_op.drop_column('image_number')

    with op.batch_alter_table('Products', schema=None) as batch_op:

        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('quantity_available',
               existing_type=sa.INTEGER(),
               nullable=False)
      

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'Productcategories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'Productsizes', ['size_id'], ['id'])
        batch_op.alter_column('quantity_available',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('size')
        batch_op.drop_column('category')

    with op.batch_alter_table('Productimages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_number', sa.INTEGER(), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('mimetype')
        batch_op.drop_column('filename')

    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('Customerorders', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('shipping_address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('order_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('Addresses', schema=None) as batch_op:
        batch_op.alter_column('postcode',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('address_line1',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('Productsizes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('size', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Productcategories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
