"""inital migration

Revision ID: b8630fa28bcc
Revises: 23e548252d34
Create Date: 2024-12-09 01:40:01.889626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8630fa28bcc'
down_revision = '23e548252d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    op.drop_table('orderedproducts')
    op.drop_table('customerorders')
    op.drop_table('productcategories')
    op.drop_table('customers')
    op.drop_table('productsizes')
    op.drop_table('products')
    op.drop_table('productimages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productimages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.VARCHAR(length=200), nullable=True),
    sa.Column('image_number', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('quantity_available', sa.INTEGER(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('size_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['productcategories.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['productsizes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productsizes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('size', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('productcategories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customerorders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('shipping_address_id', sa.INTEGER(), nullable=True),
    sa.Column('total_price', sa.FLOAT(), nullable=True),
    sa.Column('order_complete', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderedproducts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['customerorders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###
