"""add basket update images

Revision ID: dd158a80cbda
Revises: 8cdf1ff35fb7
Create Date: 2024-12-10 17:07:58.981436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd158a80cbda'
down_revision = '8cdf1ff35fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_Addresses')
    op.drop_table('_alembic_tmp_Customers')
    op.drop_table('_alembic_tmp_Customerorders')
    with op.batch_alter_table('Productimages', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Productimages', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_Customerorders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('order_date', sa.DATE(), nullable=False),
    sa.Column('shipping_address_id', sa.INTEGER(), nullable=False),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.Column('order_complete', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['Customers.id'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['Addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_alembic_tmp_Customers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('_alembic_tmp_Addresses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('address_line1', sa.VARCHAR(length=100), nullable=False),
    sa.Column('city', sa.VARCHAR(length=30), nullable=False),
    sa.Column('postcode', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['Customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
