"""initial migration

Revision ID: ec1b173c49f5
Revises: 
Create Date: 2024-10-27 22:15:07.370633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1b173c49f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assesment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('module_code', sa.String(length=10), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assesment')
    # ### end Alembic commands ###
